---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cache.nubificus.co.uk
  resources:
  - sminos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.nubificus.co.uk
  resources:
  - sminos/finalizers
  verbs:
  - update
- apiGroups:
  - cache.nubificus.co.uk
  resources:
  - sminos/status
  verbs:
  - get
  - patch
  - update
