# permissions for end users to view sminos.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: sminos-operator
    app.kubernetes.io/managed-by: kustomize
  name: sminos-viewer-role
rules:
- apiGroups:
  - cache.nubificus.co.uk
  resources:
  - sminos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.nubificus.co.uk
  resources:
  - sminos/status
  verbs:
  - get
